import { db } from '@/db';
import { events } from '@/db/schema';

async function main() {
    const now = new Date().toISOString();
    
    const sampleEvents = [
        {
            title: 'Sharma-Patel Wedding Ceremony',
            description: 'A grand traditional wedding ceremony celebrating the union of two beautiful families. Experience authentic Maharashtrian and Gujarati rituals, traditional music, delicious cuisine, and joyous celebrations. Join us in blessing the couple on their special day.',
            categoryId: 1,
            venueId: 1,
            managerId: 'profile_06h9p2y7j3e5d8g6s2r1v0b3w9',
            startDate: new Date('2024-12-25T10:00:00').toISOString(),
            endDate: new Date('2024-12-25T18:00:00').toISOString(),
            ticketPrice: 0,
            totalSeats: 500,
            availableSeats: 485,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
            tags: ['wedding', 'traditional', 'maharashtrian', 'gujarati', 'celebration'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Tech Summit 2024',
            description: 'India\'s premier technology conference bringing together industry leaders, innovators, and tech enthusiasts. Explore latest trends in AI, Cloud Computing, Blockchain, and Cybersecurity. Network with 800+ professionals and gain insights from expert speakers.',
            categoryId: 2,
            venueId: 3,
            managerId: 'profile_07h0q3z8k4f6e9h7t3s2w1c4x0',
            startDate: new Date('2024-12-28T09:00:00').toISOString(),
            endDate: new Date('2024-12-28T17:00:00').toISOString(),
            ticketPrice: 2500,
            totalSeats: 800,
            availableSeats: 742,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
            tags: ['technology', 'conference', 'AI', 'networking', 'innovation'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Bollywood Night Live Concert',
            description: 'An electrifying evening of Bollywood music featuring popular playback singers performing chart-topping hits. Dance to your favorite songs, enjoy spectacular stage performances, and immerse yourself in the magic of Hindi cinema music.',
            categoryId: 3,
            venueId: 5,
            managerId: 'profile_08h1r4a9l5g7f0i8u4t3x2d5y1',
            startDate: new Date('2025-01-05T19:00:00').toISOString(),
            endDate: new Date('2025-01-05T23:00:00').toISOString(),
            ticketPrice: 1500,
            totalSeats: 1000,
            availableSeats: 823,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800',
            tags: ['bollywood', 'concert', 'music', 'live', 'entertainment'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Kids Birthday Bash - Aarav Turns 7',
            description: 'A fun-filled birthday celebration for little Aarav with exciting games, magic shows, face painting, and a themed party setup. Join us for cake cutting, dancing, and creating wonderful memories. Kids-friendly menu and goodie bags for all attendees.',
            categoryId: 4,
            venueId: 7,
            managerId: 'profile_06h9p2y7j3e5d8g6s2r1v0b3w9',
            startDate: new Date('2025-01-10T16:00:00').toISOString(),
            endDate: new Date('2025-01-10T20:00:00').toISOString(),
            ticketPrice: 500,
            totalSeats: 80,
            availableSeats: 68,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800',
            tags: ['birthday', 'kids', 'party', 'celebration', 'family'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Digital Marketing Conference',
            description: 'Master the art of digital marketing in 2024. Learn cutting-edge strategies in SEO, social media marketing, content creation, and analytics. Industry experts share real-world case studies and actionable insights. Perfect for marketers and business owners.',
            categoryId: 5,
            venueId: 2,
            managerId: 'profile_07h0q3z8k4f6e9h7t3s2w1c4x0',
            startDate: new Date('2025-01-15T10:00:00').toISOString(),
            endDate: new Date('2025-01-15T18:00:00').toISOString(),
            ticketPrice: 3500,
            totalSeats: 300,
            availableSeats: 267,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800',
            tags: ['marketing', 'digital', 'conference', 'SEO', 'business'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Ganesh Chaturthi Celebration',
            description: 'Join the grand Ganesh Chaturthi festival celebration with traditional rituals, aarti, bhajans, and cultural programs. Experience the divine atmosphere with prasad distribution, community participation, and vibrant decorations. Free entry for all devotees.',
            categoryId: 6,
            venueId: 4,
            managerId: 'profile_08h1r4a9l5g7f0i8u4t3x2d5y1',
            startDate: new Date('2025-01-20T17:00:00').toISOString(),
            endDate: new Date('2025-01-20T22:00:00').toISOString(),
            ticketPrice: 0,
            totalSeats: 600,
            availableSeats: 572,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800',
            tags: ['festival', 'ganesh', 'cultural', 'traditional', 'celebration'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Professional Photography Workshop',
            description: 'Intensive hands-on workshop covering advanced photography techniques, lighting, composition, and post-processing. Learn from award-winning photographers. Includes practical outdoor shoots, portfolio reviews, and personalized feedback. Limited seats for quality interaction.',
            categoryId: 7,
            venueId: 6,
            managerId: 'profile_06h9p2y7j3e5d8g6s2r1v0b3w9',
            startDate: new Date('2025-01-25T09:00:00').toISOString(),
            endDate: new Date('2025-01-25T17:00:00').toISOString(),
            ticketPrice: 2000,
            totalSeats: 50,
            availableSeats: 38,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
            tags: ['photography', 'workshop', 'learning', 'creative', 'professional'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Inter-Office Cricket Tournament',
            description: 'Annual corporate cricket tournament featuring teams from Pune\'s leading IT companies. Enjoy thrilling matches, team spirit, and friendly competition. Includes refreshments, prize distribution, and networking opportunities. Bring your colleagues and cheer for your team!',
            categoryId: 8,
            venueId: 10,
            managerId: 'profile_07h0q3z8k4f6e9h7t3s2w1c4x0',
            startDate: new Date('2025-02-01T08:00:00').toISOString(),
            endDate: new Date('2025-02-01T18:00:00').toISOString(),
            ticketPrice: 200,
            totalSeats: 200,
            availableSeats: 178,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
            tags: ['cricket', 'sports', 'tournament', 'corporate', 'team-building'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Startup Networking Evening',
            description: 'Connect with entrepreneurs, investors, and industry mentors in Pune\'s startup ecosystem. Share ideas, explore collaborations, and discover funding opportunities. Includes startup pitch sessions, panel discussions, and one-on-one networking. Currently in progress!',
            categoryId: 2,
            venueId: 9,
            managerId: 'profile_08h1r4a9l5g7f0i8u4t3x2d5y1',
            startDate: new Date('2024-12-20T18:00:00').toISOString(),
            endDate: new Date('2024-12-20T22:00:00').toISOString(),
            ticketPrice: 1000,
            totalSeats: 150,
            availableSeats: 132,
            status: 'ongoing',
            imageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800',
            tags: ['startup', 'networking', 'entrepreneurship', 'business', 'investment'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Classical Music Concert - Raag Darbar',
            description: 'An enchanting evening of Indian classical music featuring renowned artists performing traditional ragas. Experience the beauty of tabla, sitar, and vocal performances in an intimate setting. Perfect for classical music enthusiasts and cultural connoisseurs.',
            categoryId: 3,
            venueId: 8,
            managerId: 'profile_09h2s5b0m6h8g1j9v5u4y3e6z2',
            startDate: new Date('2025-02-08T19:00:00').toISOString(),
            endDate: new Date('2025-02-08T22:00:00').toISOString(),
            ticketPrice: 800,
            totalSeats: 250,
            availableSeats: 223,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800',
            tags: ['classical', 'music', 'concert', 'traditional', 'cultural'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Annual Food Festival - Taste of Pune',
            description: 'Celebrate Pune\'s rich culinary heritage with 50+ food stalls offering authentic Maharashtrian delicacies, street food, fusion cuisine, and desserts. Live cooking demonstrations, food competitions, and cultural performances. A paradise for food lovers! Event ongoing now!',
            categoryId: 6,
            venueId: 1,
            managerId: 'profile_07h0q3z8k4f6e9h7t3s2w1c4x0',
            startDate: new Date('2024-12-22T11:00:00').toISOString(),
            endDate: new Date('2024-12-22T21:00:00').toISOString(),
            ticketPrice: 300,
            totalSeats: 500,
            availableSeats: 456,
            status: 'ongoing',
            imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
            tags: ['food', 'festival', 'cuisine', 'cultural', 'maharashtrian'],
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Yoga and Wellness Retreat',
            description: 'Rejuvenate your mind, body, and soul with a comprehensive wellness retreat. Expert-led yoga sessions, meditation, pranayama, nutrition workshops, and holistic health consultations. Includes healthy meals, wellness kit, and personalized wellness plan.',
            categoryId: 7,
            venueId: 3,
            managerId: 'profile_10h3t6c1n7i9h2k0w6v5z4f7a3',
            startDate: new Date('2025-02-15T07:00:00').toISOString(),
            endDate: new Date('2025-02-15T15:00:00').toISOString(),
            ticketPrice: 1800,
            totalSeats: 100,
            availableSeats: 87,
            status: 'upcoming',
            imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
            tags: ['yoga', 'wellness', 'meditation', 'health', 'retreat'],
            createdAt: now,
            updatedAt: now,
        },
    ];

    await db.insert(events).values(sampleEvents);
    
    console.log('✅ Events seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});